### PR TITLE
Lha ssh output crash

### LINKED ISSUE #297: LHA crashes when it can't parse ssh output correctly
We got an INC recently where a user was encountering this issue.  It turns out it was an issue in their ~/.bashrc file that was the cause. 

I was unable to replicate with at statement like this`./apps/python/3.6-conda5.2/etc/profile.d/conda.sh` (which errors saying no such file or directory).  I believe the user had a similar statement, trying to source a conda environment file, but again I cannot replicate with that alone so there's something else I'm missing.

```text
#<NoMethodError: undefined method `start_with?' for nil:NilClass>
/opt/ood/ondemand/root/usr/share/gems/2.7/ondemand/2.0.10/gems/ood_core-0.17.1/lib/ood_core/job/adapters/linux_host/launcher.rb:259:in `block in list_remote_tmux_session'
/opt/ood/ondemand/root/usr/share/gems/2.7/ondemand/2.0.10/gems/ood_core-0.17.1/lib/ood_core/job/adapters/linux_host/launcher.rb:258:in `select'
/opt/ood/ondemand/root/usr/share/gems/2.7/ondemand/2.0.10/gems/ood_core-0.17.1/lib/ood_core/job/adapters/linux_host/launcher.rb:258:in `list_remote_tmux_session'
/opt/ood/ondemand/root/usr/share/gems/2.7/ondemand/2.0.10/gems/ood_core-0.17.1/lib/ood_core/job/adapters/linux_host/launcher.rb:90:in `block in list_remote_sessions'
/opt/ood/ondemand/root/usr/share/gems/2.7/ondemand/2.0.10/gems/ood_core-0.17.1/lib/ood_core/job/adapters/linux_host/launcher.rb:89:in `map'
/opt/ood/ondemand/root/usr/share/gems/2.7/ondemand/2.0.10/gems/ood_core-0.17.1/lib/ood_core/job/adapters/linux_host/launcher.rb:89:in `list_remote_sessions'
/opt/ood/ondemand/root/usr/share/gems/2.7/ondemand/2.0.10/gems/ood_core-0.17.1/lib/ood_core/job/adapters/linux_host.rb:95:in `info_all'
/opt/ood/ondemand/root/usr/share/gems/2.7/ondemand/2.0.10/gems/ood_core-0.17.1/lib/ood_core/job/adapters/linux_host.rb:151:in `info' 
```

### PR DESCRIPTION
**Pull request by Oglopf**
Fixes #297. Still not working in the browser when trying to launch codeserver, and only codeserver gives the issue.

### CODE REVIEW

File: spec/job/adapters/linux_host/launcher_spec.rb [hunk 1]
```diff
@@ -159,6 +159,22 @@ def content
...
+
+User           Jobs    Dollars    Status
+-------------  ------  ---------  --------
+alanc          0       0.0        ACTIVE
+johrstrom      0       0.0        ACTIVE
+johrstromtest  0       0.0        ACTIVE
+travert        0       0.0        ACTIVE
+--             --      --
+TOTAL          0       0.0
+launched-by-ondemand-a8e85cd4-791d-49fa-8be1-5bd5c1009d70,1569609529,175138" }
```
Comment (johrstrom) [inline spec/job/adapters/linux_host/launcher_spec.rb:177]: Can we turn this into a HEREDOC, they just look nicer and can be tabbed over to the right indentation.

Plus I think the test can be a little bit tougher. Maybe some lines that have 1 or 2 keys not all 3. And some lines that have the seperator (and use the `"#{seperator}"` here too in case it changes in the future).

Comment (Oglopf) [reply spec/job/adapters/linux_host/launcher_spec.rb]: Added the HEREDOC and test cases for returns with missing keys. The `#{seperator}` is checked already in the tests under the var name of `sep` for the `tmux_output_{a,b,c}` cases.

File: spec/job/adapters/linux_host/launcher_spec.rb [hunk 2]
```diff
@@ -105,6 +105,28 @@ def content
...
+                 alanc 0 0.0 ACTIVE johrstrom 15 0.0 ACTIVE johrstromtest 0 0.0 ACTIVE 
+                 travert 9 0.0 ACTIVE -- -- -- TOTAL 24 0.0 owens-login01.hpc.osc.edu)
+             HEREDOC
+            }
+            it "parses remote host correctly" do
+                allow(Open3).to receive(:capture3).and_return([broken_data, '', exit_success])
+
+                expect{
+                    subject.start_remote_session(build_script).to match(/owens-login01\.hpc\.osc\.edu/)
+                }
```
Comment (johrstrom) [inline spec/job/adapters/linux_host/launcher_spec.rb:127]: You have this entire thing wrapped in the expect block.

I think you want something more like this:
```ruby
session = subject.start_remote_session(build_script)
expect(session).to match(/^launched-by-ondemand.+@owens-login01\.hpc\.osc\.edu$/)
```

Indeed when you change the test case you'll see that that `parse_hostname` isn't working right.

File: lib/ood_core/job/adapters/linux_host/templates/script_wrapper.erb.sh [hunk 3]
```diff
@@ -14,6 +14,7 @@ if [ -z "$hostname" ]; then
 fi
 
 echo $hostname
+echo ""
```
Comment (johrstrom) [inline lib/ood_core/job/adapters/linux_host/templates/script_wrapper.erb.sh:17]: I think we'd want to echo before, not after right? That way we ensure that `echo $hostname` is on it's own line.

File: lib/ood_core/version.rb [hunk 4]
```diff
@@ -1,4 +1,4 @@
 module OodCore
   # The current version of {OodCore}
-  VERSION = "0.17.1"
+  VERSION = "0.17.6"
```
Comment (johrstrom) [inline lib/ood_core/version.rb:3]: Watch out for this. Seems you need to reset this file back to the master version.

File: spec/job/adapters/linux_host/launcher_spec.rb [hunk 5]
```diff
@@ -105,6 +105,39 @@ def content
                 subject.start_remote_session(build_script(native: {'submit_host_override' => alt_submit_host}))
             end
         end
+
+        context "When tmux returns extra data along with the hostname it" do
+            # let(:broken_data) { 
+            #     <<~HEREDOC
+            #     Code Server (launched-by-ondemand-74542f25-fa6e-4e33-8e47-
```
Comment (johrstrom) [inline spec/job/adapters/linux_host/launcher_spec.rb:112]: Looks like you need to get rid of this commented broken_data.

File: spec/job/adapters/linux_host/launcher_spec.rb [hunk 6]
```diff
@@ -160,6 +194,30 @@ def content
...
+            alanc          0       0.0        ACTIVE
+            johrstrom      0       0.0        ACTIVE
+            johrstromtest  0       0.0        ACTIVE
+            travert        0       0.0        ACTIVE
+            --             --      --
+            TOTAL          0       0.0
+            launched-by-ondemand-a8e85cd4-791d-49fa-8be1-5bd5c1009d70,1569609529,175138
+            launched-by-ondemand-a8e85cd4-791d-49fa-8be1-5bd5c1009d70,1569609529
+            launched-by-ondemand-a8e85cd4-791d-49fa-8be1-5bd5c1009d70
+            a8e85cd4-791d-49fa-8be1-5bd5c1009d70,1569609529,175138
```
Comment (johrstrom) [inline spec/job/adapters/linux_host/launcher_spec.rb:217]: Be sure to use `#{sep}` here so that when the separator changes we don't need to update these test cases.
